name: notion_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  envied: ^0.5.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  http: ^1.1.0
  riverpod_annotation: ^2.2.0
  riverpod: ^2.4.9

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true
